### PR TITLE
integrate utils

### LINKED ISSUE #2: Integrate `FullMath`

### PR DESCRIPTION
**Pull request by kafeikui**
Close #2 #3 #4 #5

### CODE REVIEW

**Review by neptune-v — CHANGES_REQUESTED** [review]
I am not sure I understand this.
I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?

**Comment by kafeikui** [comment]
> I am not sure I understand this.
> I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
> Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?

1. Some classes in `@uniswap/v3-sdk` are not exported but needed like `SwapMath` and `InternalConstants`.
2. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.

**Comment by neptune-v** [comment]
> > I am not sure I understand this.
> > I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
> > Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?
> 
> 1. Some classes in `@uniswap/v3-sdk` are not exported but needed like `SwapMath` and `InternalConstants`.
> 2. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.

It seems `SwapMath` is globally exported in the SDK.
Please remove the code we don't need, less code, less bug, less code that's not being executed, less confusion in the codebase.
Not executed code = obsolete code.

**Comment by kafeikui** [comment]
> > > I am not sure I understand this.
> > > I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
> > > Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?
> > 
> > 
> > 
> > 1. Some classes in `@uniswap/v3-sdk` are not exported but needed like `SwapMath` and `InternalConstants`.
> > 2. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.
> 
> It seems `SwapMath` is globally exported in the SDK.
> 
> https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/swapMath.ts#L9
> https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/index.ts#L2
> 
> Please remove the code we don't need, less code, less bug, less code that's not being executed, less confusion in the codebase.
> Not executed code = obsolete code.

From my attempts, I can't import it. Could you check it?
https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/index.ts

**Comment by neptune-v** [comment]
> > > > I am not sure I understand this.
> > > > I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
> > > > Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?
> > > 
> > > 
> > > 
> > > 1. Some classes in `@uniswap/v3-sdk` are not exported but needed like `SwapMath` and `InternalConstants`.
> > > 2. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.
> > 
> > 
> > It seems `SwapMath` is globally exported in the SDK.
> > https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/swapMath.ts#L9
> > https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/index.ts#L2
> > Please remove the code we don't need, less code, less bug, less code that's not being executed, less confusion in the codebase.
> > Not executed code = obsolete code.
> 
> From my attempts, I can't import it. Could you check it?
> https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/index.ts
> Besides, I'd like to know your thoughts about this concern.
> 
> > >
> 
> 1. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.

I am only seeing `mulDiv`,  `getAmount0Delta`, and `getAmount1Delta`, in such scenarios, you can create `private` helper methods in the class that calls the math functions. If more than one classes are calling these functions, move the helpers out to its individual file.

**Comment by kafeikui** [comment]
> > > > > I am not sure I understand this.
> > > > > I thought we could directly use the SDK instead of wrapping the method even when the input parameters are the same?
> > > > > Why are we copying and pasting when the code is identical instead of directly import the sdk wherever we need the math functions?
> > > > 
> > > > 
> > > > 
> > > > 1. Some classes in `@uniswap/v3-sdk` are not exported but needed like `SwapMath` and `InternalConstants`.
> > > > 2. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.
> > > 
> > > 
> > > It seems `SwapMath` is globally exported in the SDK.
> > > https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/swapMath.ts#L9
> > > https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/index.ts#L2
> > > Please remove the code we don't need, less code, less bug, less code that's not being executed, less confusion in the codebase.
> > > Not executed code = obsolete code.
> > 
> > 
> > From my attempts, I can't import it. Could you check it?
> > https://github.com/Uniswap/uniswap-v3-sdk/blob/main/src/utils/index.ts
> > Besides, I'd like to know your thoughts about this concern.
> > > >
> > 
> > 
> > 
> > 1. Current structure and method signature is identical to things in smart contract while structure and method signature in `@uniswap/v3-sdk` is not 100% identical, like lucking one or two method in a class. For those functions with the same input parameters, it's fine to call directly by importing them. But for consistency of structure, I choose to wrap them as well.
> 
> I am only seeing `mulDiv`, `getAmount0Delta`, and `getAmount1Delta`, in such scenarios, you can create `private` helper methods in the class that calls the math functions. If more than one classes are calling these functions, move the helpers out to its individual file.
> 
> For importing, does `@uniswap/v3-sdk/swapMath.ts` work?

Still not work for importing and I don't think it's allowed for module management.
Actually I can accept principle you addressed, just a question to add, if we import both `FullMath` from the library and `FullMath` we built as helper in a class, then one of them has to be renamed to an alias or to be imported from another namespace, but actually these two classes share the same role in function level. Will it be annoying?

**Comment by neptune-v** [comment]
I think we have 2 options here:

1. Copy and paste all the code that we can use and directly modify them to fit our needs instead of partially wrapping them and partially re-writing some.

2. Fork the SDK then branch-out to make the modifications, then use git-submodule to directly reference the forked version of the source code.

I think 1 is easier. It's up to you.

**Comment by kafeikui** [comment]
> I think we have 2 options here:
> 
> 1. Copy and paste all the code that we can use and directly modify them to fit our needs instead of partially wrapping them and partially re-writing some.
> 2. Fork the SDK then branch-out to make the modifications, then use git-submodule to directly reference the forked version of the source code. The nice thing about this is that we can incorporate new updates more easily, and keep the integrity of the SDK at the same time.
> 
> I think 1 might be easier. 2 is more straightforward, it's up to you.

I think I prefer option 1. Because I think the chance of `@uniswap/v3-sdk` repo getting updated is low, even it has, the updates unlikely relate to utils. Besides, if we make a submodule of `@uniswap/v3-sdk`, then what role of this module should be? It's not for integrating use as `@uniswap/v3-sdk` did. If we take it as utils library, then why should it fork `@uniswap/v3-sdk`? So if we choose option 1, does it mean we should remove dependency of `@uniswap/v3-sdk` and just copy and paste all the code we need?

**Comment by neptune-v** [comment]
> > I think we have 2 options here:
> > 
> > 1. Copy and paste all the code that we can use and directly modify them to fit our needs instead of partially wrapping them and partially re-writing some.
> > 2. Fork the SDK then branch-out to make the modifications, then use git-submodule to directly reference the forked version of the source code. The nice thing about this is that we can incorporate new updates more easily, and keep the integrity of the SDK at the same time.
> > 
> > I think 1 might be easier. 2 is more straightforward, it's up to you.
> 
> I think I prefer option 1. Because I think the chance of `@uniswap/v3-sdk` repo getting updated is low, even it has, the updates unlikely relate to utils. Besides, if we make a submodule of `@uniswap/v3-sdk`, then what role of this module should be? It's not for integrating use as `@uniswap/v3-sdk` did. If we take it as utils library, then why should it fork `@uniswap/v3-sdk`? So if we choose option 1, does it mean we should remove dependency of `@uniswap/v3-sdk` and just copy and paste all the code we need?

OK, that's reasonable, I see the SDK utils folder is mostly self-contained meaning it does not have a lot of other dependencies.
You can go ahead with the process, keep in mind to make minimum changes to the copied&pasted code.
Also copy their license from the root as well.

**Review by neptune-v — APPROVED** [review]
LGTM

**Pull request merged**
