### PR TITLE
Add typechain

### PR DESCRIPTION
**Pull request by ryuheimat**
- add hardhat typechain plugin
- Uniswap typechain factories

### CODE REVIEW

**Review by neptune-v — COMMENTED** [review]
I read about `.d.ts` files which are declarations of types and interfaces, do you think we can provide our own implementation to these for the simulator so we can directly run uniswap v3 contract tests that way?

**Comment by ryuheimat** [comment]
We don t need to make implementations for those interfaces. There is a factory classes which can make Contract.
We can use that to interact with contracts, and can be used to test uni v3 contracts

**Comment by neptune-v** [comment]
The goal is that ideally, to re-use the tests from UniSwap V3 smart contracts to directly test against our simulator.

spec test -> generated typechain stub -> pool contract
spec test -> modified typechain stub -> simulator

This way, we can reuse most of the tests without re-writing everything. (There are 2000+ lines of tests for the pool alone)

**Comment by neptune-v** [comment]
Closing this PR for now per our discussion in Slack.

**Pull request closed without merging**
